reporting_patient_states:
  description: "Monthly summary of a patient's information and health indicators. This table has one row per patient, per month, from the month of the patient's registration."
  columns:
    patient_id: "ID of the patient"
    recorded_at: "Time (in UTC) at which the patient was registered"
    status: "active, dead, migrated, etc"
    gender: "Gender of the patient"
    age: "Age of the patient as entered by a nurse"
    age_updated_at: "Time (in UTC) at which the field 'age' was last updated"
    date_of_birth: "Date of birth of the patient"
    current_age: "Patient's age as of today, based on 'age', 'age_updated_at' and 'date_of_birth'. This will have the same value for a patient across all rows."
    month_date: "The reporting month for this row, represented as the date at the beginning of the month"
    month: "Month (1-12) of year"
    quarter: "Quarter (1-4) of year"
    year: "Year in YYYY format"
    month_string: "String that represents a month, in YYYY-MM format"
    quarter_string: "String that represents a quarter, in YYYY-Q format"
    hypertension: "Has the patient been diagnosed with hypertension? Values can be yes, no, unknown, or null if the data is unavailable."
    prior_heart_attack: "Has the patient had a heart attack? Values can be yes, no, unknown, or null if the data is unavailable."
    prior_stroke: "Has the patient has had a stroke? Values can be yes, no, unknown, or null if the data is unavailable."
    chronic_kidney_disease: "Has the patient had a chronic kidney disease? Values can be yes, no, unknown, or null if the data is unavailable."
    receiving_treatment_for_hypertension: "Was the patient already receiving treatment for hypertension during registration? Values can be yes, no, unknown, or null if the data is unavailable."
    diabetes: "Has the patient been diagnosed with diabetes? Values can be yes, no, unknown, or null if the data is unavailable."
    assigned_facility_id: "ID of the patient's assigned facility"
    assigned_facility_size: "Size of the patient's assigned facility"
    assigned_facility_type: "Type of the patient's assigned facility"
    assigned_facility_slug: "Human readable ID of the patient's assigned facility"
    assigned_facility_region_id: "Region ID of the patient's assigned facility"
    assigned_block_slug: "Human readable ID of the patient's assigned facility's block"
    assigned_block_region_id: "ID of the patient's assigned facility's block"
    assigned_district_slug: "Human readable ID of the patient's assigned facility's district"
    assigned_district_region_id: "ID of the patient's assigned facility's district"
    assigned_state_slug: "Human readable ID of the patient's assigned facility's state"
    assigned_state_region_id: "ID of the patient's assigned facility's state"
    assigned_organization_slug: "Human readable ID of the patient's assigned facility's organization"
    assigned_organization_region_id: "ID of the patient's assigned facility's organization"
    registration_facility_id: "ID of the patient's registration facility"
    registration_facility_size: "Size of the patient's registration facility"
    registration_facility_type: "Type of the patient's registration facility"
    registration_facility_slug: "Human readable ID of the patient's registration facility"
    registration_facility_region_id: "Region ID of the patient's registration facility"
    registration_block_slug: "Human readable ID of the patient's registration facility's block"
    registration_block_region_id: "ID of the patient's registration facility's block"
    registration_district_slug: "Human readable ID of the patient's registration facility's district"
    registration_district_region_id: "ID of the patient's registration facility's district"
    registration_state_slug: "Human readable ID of the patient's registration facility's state"
    registration_state_region_id: "ID of the patient's registration facility's state"
    registration_organization_slug: "Human readable ID of the patient's registration facility's organization"
    registration_organization_region_id: "ID of the patient's registration facility's organization"
    blood_pressure_id: "ID of the latest BP as of this month. Use this to join with the blood_pressures table."
    bp_facility_id: "ID of the facility at which the latest BP was recorded as of this month"
    bp_recorded_at: "Time (in UTC) at which the latest BP as of this month was recorded"
    systolic: "Systolic of the latest BP as of this month"
    diastolic: "Diastolic of the latest BP as of this month"
    encounter_id: "ID of the latest encounter as of this month. Use this to join with the encounters table."
    encounter_recorded_at: "Time (in UTC) at which the latest encounter as of this month was recorded"
    prescription_drug_id: "ID of the latest prescription drug as of this month. Use this to join with the prescription drugs table."
    prescription_drug_recorded_at: "Time (in UTC) at which the latest prescription drug as of this month was recorded"
    appointment_id: "ID of the latest appointment as of this month. Use this to join with the appointments table."
    appointment_recorded_at: "Time (in UTC) at which the latest appointment as of this month was recorded"
    visited_facility_ids: "IDs of the facilities visited this month"
    months_since_registration: "Number of months since registration. If a patient was registered on 31st Jan, it would be 1 month since registration on 1st Feb."
    quarters_since_registration: "Number of quarters since registration. If a patient was registered on 31st Dec, it would be 1 quarter since registration on 1st Jan."
    months_since_visit: "Number of months since the patient's last visit. If a patient visited on 31st Jan, it would be 1 month since the visit on 1st Feb."
    quarters_since_visit: "Number of quarters since the patient's last visit. If a patient visited on 31st Jan, it would be 1 quarter since the visit on 1st Jan."
    months_since_bp: "Number of months since the patient's last BP recording. If a patient had a BP reading on 31st Jan, it would be 1 month since BP on 1st Feb."
    quarters_since_bp: "Number of quarters since the patient's last BP recording. If a patient had a BP reading on 31st Jan, it would be 1 quarter since BP on 1st Jan."
    last_bp_state: "The state of the last BP recorded: controlled, uncontrolled, or unknown"
    htn_care_state: "Is the patient under_care, lost_to_follow_up, or dead as of this month?"
    htn_treatment_outcome_in_last_3_months: "For the visiting period of the last 3 months, is this patient's treatment outcome controlled, uncontrolled, missed_visit, or visited_no_bp?"
    htn_treatment_outcome_in_last_2_months: "For the visiting period of the last 2 months, is this patient's treatment outcome controlled, uncontrolled, missed_visit, or visited_no_bp?"
    htn_treatment_outcome_in_quarter: "For the visiting period of the current quarter, is this patient's treatment outcome controlled, uncontrolled, missed_visit, or visited_no_bp?"
    titrated: "True, if the patient had an increase in dosage of any hypertension drug in a visit this month."
reporting_facilities:
  description: "List of Simple facililities with size, type, and geographical information. These facilities are used to segment reports by region."
  columns:
    facility_id: "ID of the facility"
    facility_name: "Name of the facility"
    facility_type: "Type of the facility (eg. 'District Hospital')"
    facility_size: "Size of the facility (community, small, medium, large)"
    facility_region_id: "ID of the facility region"
    facility_region_name: "Name of the facility region. Usually the same as the facility name"
    facility_region_slug: "Human readable ID of the facility region"
    block_region_id: "ID of the block region that the facility is in"
    block_name: "Name of the block region that the facility is in"
    block_slug: "Human readable ID of the block region that the facility is in"
    district_id: "ID of the facility group that the facility is in"
    district_region_id: "ID of the district region that the facility is in"
    district_name: "Name of the district region that the facility is in"
    district_slug: "Human readable ID of the district region that the facility is in"
    state_region_id: "ID of the state region that the facility is in"
    state_name: "Name of the state region that the facility is in"
    state_slug: "Human readable ID of the state region that the facility is in"
    organization_id: "ID of the organization that the facility is in"
    organization_region_id: "ID of the organization region that the facility is in"
    organization_name: "Name of the organization region that the facility is in"
    organization_slug: "Human readable ID of the organization region that the facility is in"
reporting_months:
  description: "List of calendar months with relevant calendar information. These months are used to segment reports by time into monthly or quarterly reports."
  columns:
    month_date: "A date representing the first day of the month"
    month: "The ordinal number of the month in the year. Eg. January = 1, February = 2, March = 3, etc."
    quarter: "The quarter number that the month falls in. Jan-Mar = 1, Apr-June = 2, Jul-Sept = 3, Oct-Dec = 4"
    year: "The calendar year"
    month_string: "A human readable version of the month in YYYY-MM format"
    quarter_string: "A human readable version of the quarter that the month is in, in YYYY-Q format"
