# These configuration values are multipliers, not absolute value

development:
  users:
    count: 2
  protocols: 2
  protocol_drugs: 2
  patients:
    count: 2
    traits:
      - overdue
      - hypertensive
    medical_histories: 1
    prescription_drugs: 1
    blood_pressures: 2
    appointments: 2

test:
  patients:
    count: 1
    traits:
      - overdue
      - hypertensive
    medical_histories: 1
    prescription_drugs: 1
    blood_pressures: 1
    appointments: 1

sandbox:
  patients:
    count: 2
    traits:
      - overdue
      - hypertensive
    medical_histories: 1
    prescription_drugs: 1
    blood_pressures: 2
    appointments: 2