:concurrency: 15
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log

:queues:
  - default
  - [analytics_warmup, 2]
  - [high, 3]
  - [low, 1]
  - [phone_number_details_queue, 1]
  - [audit_log_queue, 1]
  - [audit_log_data_queue, 1]
