version: v1.0
name: Bangladesh Demo Deployment
blocks:
  - name: Deploy to Bangladesh Demo
    task:
      secrets:
        - name: sentry-release-auth-token
        - name: argocd
      jobs:
        - name: Deploy to Bangladesh Demo
          commands:
            - checkout
            - script/argocd_deployment.sh $BD_STAGING_ARGOCD_ENDPOINT $ARGOCD_USERNAME $BD_STAGING_ARGOCD_PASSWORD $SEMAPHORE_GIT_SHA
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2204
promotions:
  - name: Bangladesh Production Deployment
    pipeline_file: bangladesh_production_deployment.yml
    auto_promote:
      when: (branch = 'master' AND result = 'passed') OR (tag =~ '^release-.*' AND result = 'passed')
