version: v1.0
name: Bangladesh Production Deployment
blocks:
  - name: Deploy to Bangladesh Production
    task:
      secrets:
        - name: sentry-release-auth-token
        - name: argocd
      jobs:
        - name: Deploy to Bangladesh Production
          commands:
            - checkout
            - script/argocd_deployment.sh $BD_PROD_ARGOCD_ENDPOINT $ARGOCD_USERNAME $BD_PROD_ARGOCD_PASSWORD $SEMAPHORE_GIT_SHA
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2204
