version: v1.0
name: India Demo Deployment
blocks:
  - name: Deploy to India Demo
    task:
      secrets:
        - name: sentry-release-auth-token
        - name: semaphore-deploy-key
      jobs:
        - name: Deploy to India Demo
          commands:
            - checkout
            - sem-version ruby 2.7.4
            - cache restore
            - yarn install
            - bundle install --deployment --path vendor/bundle
            - cache store
            - 'BRANCH=$SEMAPHORE_GIT_SHA bundle exec cap india:staging deploy'
      prologue:
        commands:
          - chmod 600 ~/.ssh/semaphore_id_rsa
          - ssh-add ~/.ssh/semaphore_id_rsa
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
promotions:
  - name: India Production Deployment
    pipeline_file: india_production_deployment.yml
    auto_promote:
      when: (branch = 'master' AND result = 'passed') OR (tag =~ '^release-.*' AND result = 'passed')
