version: v1.0
name: Sri Lanka Production Deployment k8s
blocks:
  - name: Deploy to Sri Lanka Production k8s
    task:
      secrets:
        - name: sentry-release-auth-token
        - name: argocd
      jobs:
        - name: Deploy to Sri Lanka Production k8s
          commands:
            - checkout
            - script/argocd_deployment.sh $LK_ARGOCD_ENDPOINT $ARGOCD_USERNAME $LK_ARGOCD_PASSWORD $SEMAPHORE_GIT_SHA
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2204
