name: Build & push Docker image

on:
  push:
    branches: [ docker-build ]
  pull_request:
    branches: [ docker-build ]

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: simpledotorg/server
          tags: $GITHUB_SHA, latest
          registry: docker.io
          dockerfile: Prod.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  deploy_simple_server:
    needs: docker_build_push
    runs-on: ubuntu-latest
    container:
      image: argoproj/argocd:v2.4.11
    steps:
      - name: Argocd login
        run: argocd login ${{ secrets.ARGOCD_ENDPOINT }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure --config /home/argocd/.config/argocd/config
      - name: Argocd set simple server image
        run: argocd app set server --helm-set image=simpledotorg/server:$GITHUB_SHA --config /home/argocd/.config/argocd/config
      - name: Argocd wait for sync
        run: argocd app wait server --config /home/argocd/.config/argocd/config
